create table if not exists public.transport_sync_audit_logs (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null,
  sampled_group_count integer not null default 0,
  sampled_group_ids jsonb not null default '[]'::jsonb,
  checked_request_count integer not null default 0,
  checked_order_nos jsonb not null default '[]'::jsonb,
  skipped_check_count integer not null default 0,
  skipped_checks jsonb not null default '[]'::jsonb,
  mismatch_count integer not null default 0,
  mismatches jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists transport_sync_audit_logs_checked_at_idx
  on public.transport_sync_audit_logs (checked_at desc);

create index if not exists transport_sync_audit_logs_mismatch_count_idx
  on public.transport_sync_audit_logs (mismatch_count desc, checked_at desc);
