"use strict";

function buildWave(wave, module, titles, startId) {
  return {
    wave,
    module,
    startId,
    endId: startId + titles.length - 1,
    cases: titles.map((title, index) => ({
      case_id: startId + index,
      wave,
      module,
      title
    }))
  };
}

const waveDefinitions = [
  {
    wave: 0,
    module: "env",
    titles: [
      "vercel dev starts successfully",
      "all tests use port 3001",
      "port 3000 misuse is detected",
      "home page loads",
      "login page loads",
      "register page loads",
      "pickup page loads",
      "transport board page loads",
      "service center page loads",
      "admin login page loads",
      "admin dashboard loads",
      "sync audit page loads",
      "auth login API returns JSON",
      "auth register API returns JSON",
      "public API returns JSON",
      "transport requests API returns JSON for admin",
      "transport groups API returns JSON for admin",
      "transport group members API returns JSON for admin",
      "transport sync audit logs API returns JSON",
      "key static assets do not 404",
      "session cookies behave correctly in vercel dev",
      "existing smoke script can run",
      "existing transport flow script can run",
      "baseline screenshots are saved"
    ]
  },
  {
    wave: 1,
    module: "auth-register",
    titles: [
      "email registration succeeds",
      "duplicate email registration fails",
      "invalid email format fails",
      "signup code request succeeds",
      "signup code verification fails for wrong code",
      "signup code verification fails for expired code",
      "signup code verification fails for empty code",
      "signup code request fails without turnstile",
      "turnstile failure message is correct",
      "registration fails when full name is empty",
      "registration fails when phone is empty",
      "registration fails when contact method is empty",
      "registration fails when contact handle is empty",
      "registration fails when password is too weak",
      "registration fails when passwords do not match",
      "logged-in user behavior on register page is correct",
      "registration auto-login works",
      "registration respects return_to",
      "registration lands in service center",
      "registration writes profile data",
      "double click does not create duplicate user",
      "register page works on desktop",
      "register page works on mobile",
      "registration error copy is understandable"
    ]
  },
  {
    wave: 2,
    module: "auth-session",
    titles: [
      "email password login succeeds",
      "wrong password login fails",
      "unknown email login fails",
      "empty email login fails",
      "empty password login fails",
      "login creates a stable session",
      "login can redirect to pickup page",
      "login can redirect to service center",
      "login can redirect to transport board",
      "logged-in user behavior on login page is correct",
      "logout succeeds",
      "service center is blocked after logout",
      "admin page is blocked after logout",
      "expired session redirects to login",
      "expired admin session redirects to admin login",
      "password reset request succeeds",
      "password reset request reports missing account correctly",
      "password reset fails for wrong code",
      "password reset fails for expired code",
      "password reset succeeds",
      "old password fails after reset",
      "login page desktop regression passes",
      "login page mobile regression passes",
      "reset password page desktop and mobile regression passes"
    ]
  },
  {
    wave: 3,
    module: "navigation",
    titles: [
      "home page loads correctly",
      "home immediate consult goes to WeChat search guidance",
      "home login entry works",
      "home register entry works",
      "home pickup entry works",
      "home navigation has no dead links",
      "language switch does not break core entries",
      "service center quick links load correctly",
      "service center shows pickup entry",
      "service center shows storage entry",
      "service center shows profile entry",
      "service center hides membership entry",
      "service center logout button works",
      "service center recent records entry works",
      "unauthenticated service center redirects to login",
      "service center pickup entry works after login",
      "service center profile entry works after login",
      "desktop navigation works",
      "mobile navigation works",
      "logged-in navigation state is correct",
      "logged-out navigation state is correct",
      "home to transport board path is correct",
      "home to auth path is correct",
      "entry copy matches current capability"
    ]
  },
  {
    wave: 4,
    module: "pickup-board",
    titles: [
      "pickup hero renders correctly",
      "pickup hero main CTA goes to transport board",
      "pickup hero WeChat consult works",
      "pickup hero hides extra launch button",
      "live board title area renders correctly",
      "desktop live board columns are balanced",
      "desktop primary CTA is visually dominant",
      "desktop primary CTA hover animation works",
      "secondary CTA has lower hierarchy",
      "recent-three notice is visually obvious",
      "recent-three notice explains preview-only scope",
      "recent-three notice points to full board",
      "pickup page preview loads recent groups",
      "mobile pickup preview cards render",
      "mobile preview cards do not overflow",
      "mobile preview card field order is correct",
      "mobile preview cards avoid duplicate time row",
      "flow modal opens correctly",
      "flow modal closes correctly",
      "flow modal desktop layout is correct",
      "flow modal mobile layout is correct",
      "transport board list loads correctly",
      "transport board shows only public groups",
      "transport board sort is correct",
      "transport board pagination works",
      "transport board empty state works",
      "transport board error state works",
      "pickup page desktop layout regression passes",
      "pickup page mobile layout regression passes",
      "pickup and transport board round-trip path works"
    ]
  },
  {
    wave: 5,
    module: "transport-create-form",
    titles: [
      "pickup creation succeeds",
      "dropoff creation succeeds",
      "required field validation works",
      "missing flight number fails",
      "invalid flight number format is handled",
      "missing time fails",
      "invalid time format fails",
      "missing airport fails",
      "missing terminal fails",
      "missing contact method fails",
      "missing destination fails",
      "minimum passenger boundary works",
      "maximum passenger boundary works",
      "luggage boundary works",
      "note length boundary works",
      "missing email field fails",
      "missing phone field fails",
      "contact preference boundary works",
      "unauthenticated form access is blocked",
      "login returns to form correctly",
      "desktop create form works",
      "mobile create form works",
      "submit loading state works",
      "submit failure copy is reasonable",
      "double click does not create duplicate orders",
      "refresh after edit behaves reasonably",
      "back navigation keeps key context",
      "browser back after fill is predictable",
      "success message after submit is correct",
      "create flow does not expose admin-only fields"
    ]
  },
  {
    wave: 6,
    module: "transport-create-sync",
    titles: [
      "create flow generates an order number",
      "created order is persisted",
      "single-member group is auto-created",
      "single-member group status is correct",
      "new order status is correct",
      "created order appears on transport board",
      "created order appears in recent three preview",
      "created order appears in admin requests",
      "created group appears in admin groups",
      "created order appears in service center",
      "service center recent record appears",
      "terminal summary is correct",
      "flight summary is correct",
      "airport display fields are correct",
      "shareable true stays joinable",
      "shareable false stays non-joinable",
      "visible_on_frontend behavior is correct",
      "public board hides private email",
      "public board hides private phone",
      "failed create does not leave dirty data",
      "failed form submit does not create empty group",
      "recent record order is correct after create",
      "public board counts are correct after create",
      "transport board status display is correct after create",
      "admin request detail is complete after create",
      "service center detail is complete after create",
      "pickup then dropoff boundary is correct",
      "dropoff then pickup boundary is correct",
      "multiple users can create without data mixing",
      "create screenshots and evidence map correctly"
    ]
  },
  {
    wave: 7,
    module: "transport-join",
    titles: [
      "joinable pickup group can be joined",
      "joinable dropoff group can be joined",
      "join preview succeeds",
      "join preview returns complete data",
      "join preview and submit stay consistent",
      "service type mismatch is rejected",
      "airport mismatch is rejected",
      "date mismatch is rejected",
      "time window mismatch is rejected",
      "full group is rejected",
      "closed group is rejected",
      "cancelled group is rejected",
      "shareable false target is rejected",
      "same-account future duplicate rule applies",
      "different terminal can still join",
      "different terminal surcharge is correct",
      "unauthenticated join is blocked",
      "login returns to join flow correctly",
      "join success message is correct",
      "join failure message is correct",
      "desktop join flow works",
      "mobile join flow works",
      "concurrent join boundary is correct",
      "last available seat race is handled correctly",
      "refresh during join is predictable",
      "join returns to transport board correctly",
      "join returns to service center correctly",
      "join API failure does not break UI",
      "join flow does not leak other users private data",
      "join result is recorded in the ledger"
    ]
  },
  {
    wave: 8,
    module: "transport-post-join",
    titles: [
      "group member count updates after join",
      "seat count updates after join",
      "order status changes to matched after join",
      "group status changes to active after join",
      "group status changes to full when maxed",
      "transport board passenger count changes",
      "recent three preview changes after join",
      "admin request list changes after join",
      "admin group member list changes after join",
      "service center record changes after join",
      "service center recent records change after join",
      "terminal summary updates after join",
      "flight summary updates after join",
      "single-member to multi-member public display is correct",
      "full group blocks further joins",
      "closed group blocks further joins",
      "deleted group blocks further joins",
      "public board hides joiner private data",
      "service center only shows current user records",
      "admin detail matches public board after join",
      "admin detail matches service center after join",
      "time display stays consistent after join",
      "airport display stays consistent after join",
      "terminal display stays consistent after join",
      "flight number display stays consistent after join",
      "passenger and remaining display stays consistent after join",
      "join rollback is correct on failure",
      "failed join does not create orphan membership",
      "join evidence includes screenshots and API proof",
      "join regression does not break create flow"
    ]
  },
  {
    wave: 9,
    module: "service-center",
    titles: [
      "service center loads successfully",
      "service center shows current user email",
      "service center shows current user profile data",
      "service center shows only current user bookings",
      "create flow record appears in service center",
      "join flow record appears in service center",
      "deleted order disappears from service center",
      "regroup moves records correctly in service center",
      "closed group status updates in service center",
      "service center recent records are sorted correctly",
      "service center empty state is correct",
      "multiple records list behaves correctly",
      "detail button works",
      "profile page loads correctly",
      "phone update succeeds",
      "contact update succeeds",
      "profile update failure copy is correct",
      "read-only email cannot be changed",
      "unauthenticated access is blocked",
      "expired session redirects to login",
      "desktop service center layout works",
      "mobile service center layout works",
      "service center does not leak other user data",
      "service center entry copy matches status"
    ]
  },
  {
    wave: 10,
    module: "admin",
    titles: [
      "admin login succeeds",
      "admin wrong password fails",
      "unauthorized admin account is rejected",
      "admin shell loads",
      "dashboard loads",
      "dashboard cards display correctly",
      "user management list loads",
      "user search works",
      "user filtering works",
      "user detail opens",
      "manager list loads",
      "manager creation succeeds",
      "manager creation boundary failure is correct",
      "manager disable succeeds",
      "manager enable succeeds",
      "manager password reset succeeds",
      "restricted admin cannot open privileged page",
      "restricted admin cannot call privileged API",
      "admin logout succeeds",
      "admin menu has no dead links",
      "order center list loads",
      "order center transport filter works",
      "order center detail opens",
      "sync audit logs page loads",
      "sync audit filters work",
      "sync audit detail expands correctly",
      "sync audit mismatch structure renders correctly",
      "sync audit missing-table and error hints render correctly",
      "desktop admin critical pages regression passes",
      "results CSV is generated, cleanup succeeds, and email is sent"
    ]
  }
];

let nextId = 1;
const QA300_WAVES = waveDefinitions.map(definition => {
  const wave = buildWave(definition.wave, definition.module, definition.titles, nextId);
  nextId = wave.endId + 1;
  return wave;
});

const QA300_CASES = QA300_WAVES.flatMap(wave => wave.cases);

if (QA300_CASES.length !== 300) {
  throw new Error(`QA300 matrix must contain exactly 300 cases, got ${QA300_CASES.length}`);
}

module.exports = {
  QA300_WAVES,
  QA300_CASES
};
