create table if not exists public.storage_sync_audit_logs (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null,
  sampled_order_count integer not null default 0,
  sampled_order_nos jsonb not null default '[]'::jsonb,
  checked_user_order_count integer not null default 0,
  checked_order_center_count integer not null default 0,
  skipped_check_count integer not null default 0,
  skipped_checks jsonb not null default '[]'::jsonb,
  mismatch_count integer not null default 0,
  mismatches jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.storage_sync_audit_logs enable row level security;
alter table public.storage_sync_audit_logs force row level security;

revoke all on table public.storage_sync_audit_logs from public, anon, authenticated;
grant all on table public.storage_sync_audit_logs to service_role;

create index if not exists storage_sync_audit_logs_checked_at_idx
  on public.storage_sync_audit_logs (checked_at desc);

create index if not exists storage_sync_audit_logs_mismatch_count_idx
  on public.storage_sync_audit_logs (mismatch_count desc, checked_at desc);;
